//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string CommentDescription { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int CommentPlaceId { get; set; }
        public string CommentUserId { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
