//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int FavoriteId { get; set; }
        public int FavoritePlaceId { get; set; }
        public string FavoriteUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Place Place { get; set; }
    }
}
